[project]
name = "py10x"
version = "0.1.0"
description = "10x Universe Core Packages"
authors = [
    {name = "ilya-pevzner",email = "founders@10x-software.org"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "importlib-resources (>=6.5.2,<6.6.0)",
    "numpy (>=2.2.2,<2.3.0)",
    "pymongo (>=4.7.3)",
    "pytest (>=8.3.4,<8.4.0)",
    "pytest-cov (>=6.0.0,<6.1.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
