src = ["core_10x", "infra_10x", "ui_10x"]
line-length = 150

[format]
quote-style = "single"
exclude = [
    "core_10x/xnone.py",
    "core_10x/code_samples/*",
    "core_10x/manual_tests/*",
    "core_10x/experimental/*",
    "ui_10x/qt6/*",
    "ui_10x/examples/*",
    "ui_10x/py_data_browser.py",
    "ui_10x/choice.py",
    "ui_10x/table*.py",
    "ui_10x/utils.py",
]

[lint]
ignore = ["RUF013","RUF012"]
exclude = [
    "core_10x/manual_tests/*",
]
extend-select = [
  "B",   # flake8-bugbear
  "I",   # isort
  "PGH", # pygrep-hooks
  "RUF", # Ruff-specific
  "UP",  # pyupgrade
  "N",   # naming
  "F",   # pyflakes
  "C90", # complexity
]

[lint.per-file-ignores]
"ui_10x/qt6/*" = ["B011","F401","I001","B007","UP035","E713","F541","F841","RUF023","UP006","UP037","UP04","B024","B027","E731","F402","F811","F821","RUF005","UP038","N801","N802","N816"]
"ui_10x/table*.py" = ["N802","I001","F401"]
"*.pyi" = ["N801","N802"]
"*/manual_tests/*" = ["N801","N802"]
"*/examples/*" = ["N801","N802","N815"]
"*.py" = ["E731"] # lambda assignments

[lint.mccabe]
max-complexity = 13 # Flag errors (`C901`) whenever the complexity level exceeds this
